image: "hseeberger/scala-sbt:11.0.11_1.5.4_2.13.6"

test:
  script:
    sbt scalafmtCheckAll coverage test coverageReport coverageAggregate
  artifacts:
    reports:
      junit:
        - target/scala-2.13/scoverage-report/scoverage.xml
      cobertura:
        - target/scala-2.13/coverage-report/cobertura.xml

publish:
  script:
    sbt package
  artifacts:
    paths:
      - target/scala-2.13/*.jar